import type { Album } from "./ListTypes";

export const albums: Album[] = [
	{
		id: "hybrid-theory",
		label: "Hybrid Theory",
		releaseDate: "2000-10-24",
		image: "/hybrid_theory.jpg",
		url: "/hybrid-theory",
		description:
			"Hybrid Theory is the debut studio album by American rock band Linkin Park, released on October 24, 2000, by Warner Bros. Records. It was recorded at The Plant Studios in Sausalito, California, and produced by Don Gilmore. The album was a commercial success, reaching number one on the Billboard 200 chart and selling over 10 million copies in the United States alone.",
		tracks: [
			{
				id: "1",
				label: "Papercut",
				duration: "03:04",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "2",
				label: "One Step Closer",
				duration: "02:35",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "3",
				label: "With You",
				duration: "03:23",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "4",
				label: "Points of Authority",
				duration: "03:20",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "5",
				label: "Crawling",
				duration: "03:29",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "6",
				label: "Runaway",
				duration: "03:03",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "7",
				label: "By Myself",
				duration: "03:09",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "8",
				label: "In the End",
				duration: "03:36",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "9",
				label: "A Place for My Head",
				duration: "03:04",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "10",
				label: "Forgotten",
				duration: "03:04",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "11",
				label: "Cure for the Itch",
				duration: "02:37",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "12",
				label: "Pushing Me Away",
				duration: "03:11",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
		],
	},
	{
		id: "meteora",
		label: "Meteora",
		releaseDate: "2003-03-24",
		image: "/meteora.jpg",
		url: "/meteora",
		description:
			"Meteora is the second studio album by American rock band Linkin Park, released on March 24, 2003, by Warner Bros. Records. It was recorded at The Plant Studios in Sausalito, California, and produced by Don Gilmore. The album was a commercial success, reaching number one on the Billboard 200 chart and selling over 10 million copies in the United States alone.",
		tracks: [
			{
				id: "1",
				label: "Foreword",
				duration: "00:13",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "2",
				label: "Don't Stay",
				duration: "03:07",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "3",
				label: "Somewhere I Belong",
				duration: "03:33",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "4",
				label: "Lying from You",
				duration: "02:55",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "5",
				label: "Hit the Floor",
				duration: "02:44",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "6",
				label: "Easier to Run",
				duration: "03:24",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "7",
				label: "Faint",
				duration: "02:42",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "8",
				label: "Figure.09",
				duration: "03:17",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "9",
				label: "Breaking the Habit",
				duration: "03:16",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "10",
				label: "From the Inside",
				duration: "02:55",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "11",
				label: "Nobody's Listening",
				duration: "02:58",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "12",
				label: "Session",
				duration: "02:24",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "13",
				label: "Numb",
				duration: "03:05",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
		],
	},
	{
		id: "minutes-to-midnight",
		label: "Minutes to Midnight",
		releaseDate: "2007-05-14",
		image: "/minutes_to_midnight.jpg",
		url: "/minutes-to-midnight",
		description:
			"Minutes to Midnight is the third studio album by American rock band Linkin Park, released on May 14, 2007, by Warner Bros. Records. The album marked a departure from the band's previous nu-metal sound, incorporating more alternative rock and experimental elements.",
		tracks: [
			{
				id: "1",
				label: "Wake",
				duration: "01:40",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "2",
				label: "Given Up",
				duration: "03:09",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "3",
				label: "Leave Out All the Rest",
				duration: "03:29",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "4",
				label: "Bleed It Out",
				duration: "02:44",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "5",
				label: "Shadow of the Day",
				duration: "04:49",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "6",
				label: "What I've Done",
				duration: "03:25",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "7",
				label: "Hands Held High",
				duration: "03:53",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "8",
				label: "No More Sorrow",
				duration: "03:41",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "9",
				label: "Valentine's Day",
				duration: "03:16",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "10",
				label: "In Between",
				duration: "03:16",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "11",
				label: "In Pieces",
				duration: "03:38",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
			{
				id: "12",
				label: "The Little Things Give You Away",
				duration: "06:23",
				studioUrl: null,
				emilyLiveUrl: null,
				lpLiveUrl: null,
			},
		],
	},
];
