// This file is auto-generated by scripts/fetch-song-links.ts
// Do not edit manually
// Last updated: 2025-10-24T23:43:29.142Z
// Run: bun run fetch-links

export interface SongLinks {
	spotify?: string;
	youtube?: string;
	youtubeMusic?: string;
	appleMusic?: string;
}

export interface SongLinksData {
	[songId: string]: SongLinks;
}

export const songLinks: SongLinksData = {
	"hybrid-theory-1": {
		spotify: "https://open.spotify.com/track/4HvcbAR8LisalXKt7cpqE1",
		youtube: "https://www.youtube.com/watch?v=vjVkXlxsO8Q",
		youtubeMusic: "https://music.youtube.com/watch?v=vjVkXlxsO8Q",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528436568&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-2": {
		spotify: "https://open.spotify.com/track/4bYLTrlcqctyHck3fjhMgW",
		youtube: "https://www.youtube.com/watch?v=4qlCC1GOwFw",
		youtubeMusic: "https://music.youtube.com/watch?v=4qlCC1GOwFw",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590431776?i=590431778&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-3": {
		spotify: "https://open.spotify.com/track/1Q9QN6dHEDeUegsySY012f",
		youtube: "https://www.youtube.com/watch?v=M8UTS2iFXOo",
		youtubeMusic: "https://music.youtube.com/watch?v=M8UTS2iFXOo",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437421&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-4": {
		spotify: "https://open.spotify.com/track/214LJVTqrkUOGemWDGHJpr",
		youtube: "https://www.youtube.com/watch?v=jZSPAp8kCl4",
		youtubeMusic: "https://music.youtube.com/watch?v=jZSPAp8kCl4",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590431776?i=590431781&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-5": {
		spotify: "https://open.spotify.com/track/0X576XiCW9uEtko6f6VkcU",
		youtube: "https://www.youtube.com/watch?v=Gd9OhYroLN0",
		youtubeMusic: "https://music.youtube.com/watch?v=Gd9OhYroLN0",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/591534774?i=591534780&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-6": {
		spotify: "https://open.spotify.com/track/5tkHje8FGSF258gi869GcV",
		youtube: "https://www.youtube.com/watch?v=ig-fyQqf510",
		youtubeMusic: "https://music.youtube.com/watch?v=ig-fyQqf510",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437609&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-7": {
		spotify: "https://open.spotify.com/track/4SJoEhpI6C61wtUfxSHMGc",
		youtube: "https://www.youtube.com/watch?v=wWBp-nlGX1o",
		youtubeMusic: "https://music.youtube.com/watch?v=wWBp-nlGX1o",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437611&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-8": {
		spotify: "https://open.spotify.com/track/7q115ia4fQn9zonjpexWsY",
		youtube: "https://www.youtube.com/watch?v=eVTXPUF4Oz4",
		youtubeMusic: "https://music.youtube.com/watch?v=eVTXPUF4Oz4",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437613&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-9": {
		spotify: "https://open.spotify.com/track/1B8WdDScvobpFsZLfdmIE1",
		youtube: "https://www.youtube.com/watch?v=3t2WkCudwfY",
		youtubeMusic: "https://music.youtube.com/watch?v=3t2WkCudwfY",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437708&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-10": {
		spotify: "https://open.spotify.com/track/3JAu2BH8sSI46rJGzQerb6",
		youtube: "https://www.youtube.com/watch?v=HNCgBuI2eJc",
		youtubeMusic: "https://music.youtube.com/watch?v=HNCgBuI2eJc",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437709&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-11": {
		spotify: "https://open.spotify.com/track/15voDM9pGkwEvHBUecpcmo",
		youtube: "https://www.youtube.com/watch?v=qqC5sdsHLq8",
		youtubeMusic: "https://music.youtube.com/watch?v=qqC5sdsHLq8",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528436018?i=528437710&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"hybrid-theory-12": {
		spotify: "https://open.spotify.com/track/4HlMOXxwF9SYG1RoJxEjio",
		youtube: "https://www.youtube.com/watch?v=Ve1LNJEIKUE",
		youtubeMusic: "https://music.youtube.com/watch?v=Ve1LNJEIKUE",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590431776?i=590431790&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-1": {
		spotify: "https://open.spotify.com/track/4hbpxoMCp62bd1sdy7XehS",
		youtube: "https://www.youtube.com/watch?v=U6R-twDkrcI",
		youtubeMusic: "https://music.youtube.com/watch?v=U6R-twDkrcI",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590423275?i=590423280&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-2": {
		spotify: "https://open.spotify.com/track/6HZdbb05lEXLvcmee3ZXO2",
		youtube: "https://www.youtube.com/watch?v=oWfGOVWrueo",
		youtubeMusic: "https://music.youtube.com/watch?v=oWfGOVWrueo",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/1668484895?i=1668485277&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-3": {
		spotify: "https://open.spotify.com/track/3agtg0x11wPvLIWkYR39nZ",
		youtube: "https://www.youtube.com/watch?v=zsCD5XCu6CM",
		youtubeMusic: "https://music.youtube.com/watch?v=zsCD5XCu6CM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437020&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-4": {
		spotify: "https://open.spotify.com/track/4zP2e2aIzOZGEFTq1MDJmm",
		youtube: "https://www.youtube.com/watch?v=NjdgcHdzvac",
		youtubeMusic: "https://music.youtube.com/watch?v=NjdgcHdzvac",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590423275?i=590423283&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-5": {
		spotify: "https://open.spotify.com/track/3R9NKZ4jmxNjOFihSF5s7f",
		youtube: "https://www.youtube.com/watch?v=oMals9XXQY8",
		youtubeMusic: "https://music.youtube.com/watch?v=oMals9XXQY8",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590423275?i=590423284&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-6": {
		spotify: "https://open.spotify.com/track/17bgialGAwoiGj1STY4cnR",
		youtube: "https://www.youtube.com/watch?v=U5zdmjVeQzE",
		youtubeMusic: "https://music.youtube.com/watch?v=U5zdmjVeQzE",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590423275?i=590423285&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-7": {
		spotify: "https://open.spotify.com/track/4Yf5bqU3NK4kNOypcrLYwU",
		youtube: "https://www.youtube.com/watch?v=LYU-8IFcDPw",
		youtubeMusic: "https://music.youtube.com/watch?v=LYU-8IFcDPw",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437024&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-8": {
		spotify: "https://open.spotify.com/track/2DrMcGNKEY0FZqjMovGaCm",
		youtube: "https://www.youtube.com/watch?v=6dEAeCHQrBs",
		youtubeMusic: "https://music.youtube.com/watch?v=6dEAeCHQrBs",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437025&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-9": {
		spotify: "https://open.spotify.com/track/6n8TMVyFKoUmDc4apxceRD",
		youtube: "https://www.youtube.com/watch?v=v2H4l9RpkwM",
		youtubeMusic: "https://music.youtube.com/watch?v=v2H4l9RpkwM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437026&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-10": {
		spotify: "https://open.spotify.com/track/60IkVf7UfQXmt5CwkpcX8a",
		youtube: "https://www.youtube.com/watch?v=YLHpvjrFpe0",
		youtubeMusic: "https://music.youtube.com/watch?v=YLHpvjrFpe0",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437027&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-11": {
		spotify: "https://open.spotify.com/track/4m1P1BSg9nLxaWbvPhNdhw",
		youtube: "https://www.youtube.com/watch?v=QJ87793QXes",
		youtubeMusic: "https://music.youtube.com/watch?v=QJ87793QXes",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590423275?i=590423550&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-12": {
		spotify: "https://open.spotify.com/track/3sbezh9MMCQrr4KY7zw13j",
		youtube: "https://www.youtube.com/watch?v=J1KqQYsUYIk",
		youtubeMusic: "https://music.youtube.com/watch?v=J1KqQYsUYIk",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437513&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"meteora-13": {
		spotify: "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h",
		youtube: "https://www.youtube.com/watch?v=kXYiU_JCYtU",
		youtubeMusic: "https://music.youtube.com/watch?v=kXYiU_JCYtU",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528435845?i=528437514&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-1": {
		spotify: "https://open.spotify.com/track/0GkuKdv0osuL9QhfnXqVNP",
		youtube: "https://www.youtube.com/watch?v=Me7TJDHCELk",
		youtubeMusic: "https://music.youtube.com/watch?v=Me7TJDHCELk",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590427297?i=590427304&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-2": {
		spotify: "https://open.spotify.com/track/1fLlRApgzxWweF1JTf8yM5",
		youtube: "https://www.youtube.com/watch?v=0xyxtzD54rM",
		youtubeMusic: "https://music.youtube.com/watch?v=0xyxtzD54rM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975364&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-3": {
		spotify: "https://open.spotify.com/track/0sp00HSXkQyqTa6QqM0O8V",
		youtube: "https://www.youtube.com/watch?v=yZIummTz9mM",
		youtubeMusic: "https://music.youtube.com/watch?v=yZIummTz9mM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590427297?i=590427307&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-4": {
		spotify: "https://open.spotify.com/track/0UFDKFqW2oGspYeYqo9wjA",
		youtube: "https://www.youtube.com/watch?v=OnuuYcqhzCE",
		youtubeMusic: "https://music.youtube.com/watch?v=OnuuYcqhzCE",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975366&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-5": {
		spotify: "https://open.spotify.com/track/0OYcEfskah1egYHjYRvbg1",
		youtube: "https://www.youtube.com/watch?v=n1PCW0C1aiM",
		youtubeMusic: "https://music.youtube.com/watch?v=n1PCW0C1aiM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975367&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-6": {
		spotify: "https://open.spotify.com/track/18lR4BzEs7e3qzc0KVkTpU",
		youtube: "https://www.youtube.com/watch?v=8sgycukafqQ",
		youtubeMusic: "https://music.youtube.com/watch?v=8sgycukafqQ",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/258416684?i=258416690&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-7": {
		spotify: "https://open.spotify.com/track/0m7mTaFGMiKI3rBJpYknip",
		youtube: "https://www.youtube.com/watch?v=gG4P3ayBzVY",
		youtubeMusic: "https://music.youtube.com/watch?v=gG4P3ayBzVY",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975409&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-8": {
		spotify: "https://open.spotify.com/track/4CWhc9FaMMfBTt4ANjfbOf",
		youtube: "https://www.youtube.com/watch?v=rW4uBvP2Dqc",
		youtubeMusic: "https://music.youtube.com/watch?v=rW4uBvP2Dqc",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590427297?i=590427452&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-9": {
		spotify: "https://open.spotify.com/track/2vfshZvISOKy2Je7wQBWOV",
		youtube: "https://www.youtube.com/watch?v=KAFOpywZbMM",
		youtubeMusic: "https://music.youtube.com/watch?v=KAFOpywZbMM",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975411&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-10": {
		spotify: "https://open.spotify.com/track/2ysXuQd8uOfSMZcMRR5Ux4",
		youtube: "https://www.youtube.com/watch?v=YgVzhgygYfs",
		youtubeMusic: "https://music.youtube.com/watch?v=YgVzhgygYfs",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/528975362?i=528975412&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-11": {
		spotify: "https://open.spotify.com/track/7jeI6EdY0elPSNz80mAKS8",
		youtube: "https://www.youtube.com/watch?v=NaRBn6QIMcQ",
		youtubeMusic: "https://music.youtube.com/watch?v=NaRBn6QIMcQ",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590427297?i=590427477&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
	"minutes-to-midnight-12": {
		spotify: "https://open.spotify.com/track/7jeI6EdY0elPSNz80mAKS8",
		youtube: "https://www.youtube.com/watch?v=NaRBn6QIMcQ",
		youtubeMusic: "https://music.youtube.com/watch?v=NaRBn6QIMcQ",
		appleMusic:
			"https://geo.music.apple.com/de/album/_/590427297?i=590427477&mt=1&app=music&ls=1&at=1000lHKX&ct=api_http&itscg=30200&itsct=odsl_m",
	},
};
